name        : a52dec
version     : 0.7.4
release     : 4
source      :
    - http://liba52.sourceforge.net/files/a52dec-0.7.4.tar.gz : a21d724ab3b3933330194353687df82c475b5dfb997513eef4c25de6c865ec33
homepage    : http://liba52.sourceforge.net
license     : GPL-2.0
component   :
    - multimedia.audio
    - ^liba52dec: multimedia.codecs
    - ^liba52dec-devel: programming.devel
summary     :
    - a52dec CLI tools
    - ^liba52dec: Library for decoding ATSC A/52 (also known as AC-3) streams
    - ^liba52dec-devel: Development files for liba52dec 
description :
    - a52dec CLI tools
    - ^liba52dec: Library for decoding ATSC A/52 (also known as AC-3) streams
    - ^liba52dec-devel: Development files for liba52dec 
patterns   :
    - ^liba52dec:
        - /usr/lib64/lib*.so.*
    - ^liba52dec-devel:
        - /usr/include
        - /usr/lib64/lib*.so
setup      : |
    %configure --disable-static --enable-shared
build      : |
    %make
install    : |
    %make_install
